### PR TITLE
fix: fix fvm check

### PR DESCRIPTION
**Pull request by charles0122**
#312 

If fvm is already included in the project, can we consider removing the code that checks for fvm

### CODE REVIEW

**Comment by charles0122** [comment]
I have a question, if I have a version of fvm at the beginning, and then I start using sidekick, will there be a conflict, or will sidekick detect that I already have a version and not ask me to set the environment variable?

**Comment by charles0122** [comment]
Another thing is that the fvm version in sidekick is not easy to update. Is it possible to update fvm through shell without built-in fvm?

**Comment by charles0122** [comment]
#311

**Comment by aguilaair** [comment]
Yep, we can remove the FVM checking code istself

**Comment by charles0122** [comment]
I was in the process of removing code and saw that Chocolatey and Brew were only used to download fvm, so I thought I'd check their code and remove it as well. If they have other uses, please let me know.

**Comment by charles0122** [comment]
@aguilaair

**Comment by charles0122** [comment]
They can be used to download git, but the download description says to download fvm

**Review by aguilaair — APPROVED** [review]

**Comment by aguilaair** [comment]
Let's keep brew/choco for now, we should update the description though

**Comment by charles0122** [comment]
@aguilaair We can close the related issue.

**Pull request merged**
